TypeError: Button.__init__() missing 1 required positional argument: 'pin' (#461)
* Bug fixed: missing arguments. (#460)

* Bug fixed: too many digits. (#460)